use_frameworks!

platform :ios, '9.0'

target 'SFBaseUI_Example' do
  pod 'SFBaseUI', :path => '../'

  target 'SFBaseUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
  
  pod 'SFCategory', :git => 'https://github.com/jack110530/SFCategory.git', :branch => 'master'
  pod 'SFMacro', :git => 'https://github.com/jack110530/SFMacro.git', :branch => 'master'
  pod 'SFCrashInspector', :git => 'https://github.com/jack110530/SFCrashInspector.git'
    
    
    
end
