use_frameworks!

platform :ios, '9.0'

target 'SFBaseUI_Example' do
  pod 'SFBaseUI', :path => '../'

  target 'SFBaseUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
    
end
